'use client'
import { useCallback, useEffect, useState } from 'react'

type ReviewTask = { id: string; intent: string; worker_wallet: string; budget_usdt: string; submitted_at: string; evidence_urls?: string[]; proof_payload?: { formData?: Record<string,string> } }

export default function AdminReviewClient() {
  const [secret, setSecret] = useState('')
  const [tasks, setTasks] = useState<ReviewTask[]>([])
  const [authenticated, setAuthenticated] = useState(false)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { const response=await fetch('/api/admin/queue',{cache:'no-store'}); if(response.status===401){setAuthenticated(false);return} const data=await response.json(); if(!response.ok)throw new Error(data.error??'Could not load review queue'); setAuthenticated(true);setTasks(data) },[])
  useEffect(()=>{load().catch(()=>{})},[load])
  async function login(){setBusy(true);setError('');const response=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret})});const data=await response.json();if(!response.ok)setError(data.error??'Login failed');else{setSecret('');await load()}setBusy(false)}
  async function decide(id:string,action:'approve'|'reject'){setBusy(true);setError('');const response=await fetch(`/api/admin/review/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const data=await response.json();if(!response.ok)setError(data.error??'Review failed');else await load();setBusy(false)}

  if(!authenticated)return <main className="min-h-[75vh] px-5 flex items-center justify-center"><div className="card p-7 w-full max-w-md"><p className="chip text-[10px] mb-3" style={{color:'var(--warn)'}}>Restricted operations</p><h1 className="font-display text-3xl font-extrabold mb-3">Reviewer sign-in</h1><p className="text-sm mb-5" style={{color:'var(--text-muted)'}}>Exchange the operations key for a secure, time-limited session.</p><input type="password" value={secret} onChange={e=>setSecret(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')login()}} className="w-full rounded-xl px-4 py-3 mb-3" style={{background:'var(--bg-subtle)',border:'1px solid var(--border)'}} placeholder="Operations key" />{error&&<p className="text-sm mb-3" style={{color:'var(--accent)'}}>{error}</p>}<button onClick={login} disabled={busy||!secret} className="btn btn-primary w-full py-3 disabled:opacity-40">{busy?'Signing in…':'Open review queue'}</button></div></main>

  return <main className="min-h-screen p-6"><div className="max-w-5xl mx-auto"><div className="flex justify-between items-end mb-7"><div><p className="chip text-[10px] mb-2" style={{color:'var(--warn)'}}>Human verification</p><h1 className="font-display text-3xl font-extrabold">Review queue</h1><p className="text-sm mt-1" style={{color:'var(--text-muted)'}}>{tasks.length} submission{tasks.length===1?'':'s'} awaiting a decision</p></div><button className="btn btn-ghost px-4 py-2 text-sm" onClick={()=>load()}>Refresh</button></div>{error&&<p className="mb-5" style={{color:'var(--accent)'}}>{error}</p>}{tasks.length===0?<div className="card p-16 text-center"><div className="text-4xl mb-3">✓</div><p>No submissions awaiting review.</p></div>:<div className="space-y-5">{tasks.map(task=><article key={task.id} className="card p-6"><div className="flex flex-col sm:flex-row justify-between gap-4"><div><h2 className="font-display text-xl font-bold">{task.intent}</h2><p className="font-mono text-xs mt-2" style={{color:'var(--text-faint)'}}>Worker {task.worker_wallet?.slice(0,8)}… · {new Date(task.submitted_at).toLocaleString()}</p></div><strong style={{color:'var(--good)'}}>${task.budget_usdt} USDT</strong></div>{!!task.evidence_urls?.length&&<div className="grid sm:grid-cols-3 gap-3 mt-5">{task.evidence_urls.map((url,index)=><img key={url} src={url} alt={`Evidence ${index+1}`} className="w-full aspect-[4/3] object-cover rounded-xl" />)}</div>}{task.proof_payload?.formData&&<div className="grid sm:grid-cols-2 gap-3 mt-5">{Object.entries(task.proof_payload.formData).map(([key,value])=><div key={key} className="rounded-xl p-3" style={{background:'var(--bg-subtle)'}}><span className="font-mono text-[9px] uppercase" style={{color:'var(--text-faint)'}}>{key.replaceAll('_',' ')}</span><div className="font-bold mt-1">{value}</div></div>)}</div>}<div className="flex gap-3 mt-6"><button disabled={busy} onClick={()=>decide(task.id,'approve')} className="btn px-5 py-2.5 disabled:opacity-40" style={{background:'var(--good)',color:'white'}}>Approve & pay</button><button disabled={busy} onClick={()=>decide(task.id,'reject')} className="btn btn-ghost px-5 py-2.5 disabled:opacity-40">Reject</button></div></article>)}</div>}</div></main>
}
